# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# version: '3.8'

# services:
#   # CouchDB service for state database
#   couchdb0:
#     image: hyperledger/fabric-couchdb
#     environment:
#       - COUCHDB_USER=admin
#       - COUCHDB_PASSWORD=adminpw
#     ports:
#       - "5984:5984"
#     networks:
#       - fabric_test

#   # Endorsing peer for Organization 1
#   peer0.org1.example.com:
#     container_name: peer0.org1.example.com
#     image: hyperledger/fabric-peer:latest
#     environment:
#       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
#     volumes:
#       - ./docker/peercfg:/etc/hyperledger/peercfg
#       - ${DOCKER_SOCK}:/host/var/run/docker.sock
#     networks:
#       - fabric_test

#   # Validator peer for Organization 1 (Optional)
#   peer1.org1.example.com:
#     container_name: peer1.org1.example.com
#     image: hyperledger/fabric-peer:latest
#     environment:
#       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
#       - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
#     volumes:
#       - ./docker/peercfg:/etc/hyperledger/peercfg
#       - ${DOCKER_SOCK}:/host/var/run/docker.sock
#     networks:
#       - fabric_test

# networks:
#   fabric_test:
#     driver: bridge



version: '3.7'
services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock
